CREATE TABLE app_info
(

  id         BIGINT       NOT NULL PRIMARY KEY,
  db_version BIGINT       NOT NULL,
  name       VARCHAR(256) NOT NULL
);

CREATE TABLE device_type
(
  type VARCHAR(50) NOT NULL  PRIMARY KEY
);

CREATE TABLE transfer_type
(
  type VARCHAR(50) NOT NULL  PRIMARY KEY
);

INSERT INTO device_type VALUES ('MOBILE');
INSERT INTO device_type VALUES ('DESKTOP');

INSERT INTO transfer_type VALUES ('SENT');
INSERT INTO transfer_type VALUES ('RECEIVED');

INSERT INTO app_info VALUES (1, 1, 'unknown device');


CREATE TABLE device
(
  id            BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name          VARCHAR(256) NOT NULL,
  display_name  VARCHAR(256) NOT NULL WITH        DEFAULT 'Unknown Device',
  mac_address   VARCHAR(512) NOT NULL UNIQUE,
  device_type   VARCHAR(50)  NOT NULL,
  auth_hash     VARCHAR(512),
  last_known_ip VARCHAR(32)  NOT NULL,
  status        SMALLINT     NOT NULL WITH        DEFAULT 0,
  last_access   BIGINT       NOT NULL,
  FOREIGN KEY (device_type) REFERENCES device_type (type)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE transfer
(
  id               BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  device_id        BIGINT      NOT NULL,
  transfer_type    VARCHAR(50) NOT NULL,
  file_name        BIGINT      NOT NULL,
  expected_size    BIGINT      NOT NULL,
  transferred_size BIGINT      NOT NULL,
  time             BIGINT      NOT NULL,
  status           SMALLINT    NOT NULL WITH        DEFAULT 0,
  FOREIGN KEY (device_id) REFERENCES device (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (transfer_type) REFERENCES transfer_type (type)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
